# Generated by Django 2.0.5 on 2018-09-03 07:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokens', '0005_auto_20180903_0732'),
        ('supporters', '0010_auto_20180831_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.PositiveIntegerField(help_text='amount of tokens purchased by the supporter')),
                ('total', models.FloatField(blank=True, help_text='total paid for the amount of tokens')),
                ('status', models.CharField(blank=True, choices=[('paid', 'Paid'), ('pending', 'Pending'), ('canceled', 'Cancelled')], default='pending', max_length=8)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='supporters.Supporter')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tokens.Token')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
