# Generated by Django 2.0.5 on 2018-08-27 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ('created',)},
        ),
    ]
