# Generated by Django 2.0.5 on 2018-08-28 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_auto_20180827_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('pending', 'Pending'), ('canceled', 'Cancelled')], default='pending', max_length=8),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total',
            field=models.FloatField(blank=True, help_text='total paid for the amount of tokens'),
        ),
    ]
