# Generated by Django 2.0.5 on 2018-08-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_auto_20180828_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='token',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
