# Generated by Django 2.0.5 on 2018-09-03 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0005_auto_20180903_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'EUR'), ('USD', 'USD'), ('ETH', 'ETH'), ('BTC', 'BTC')], default='USD', max_length=3),
        ),
    ]
