# Generated by Django 2.0.5 on 2018-05-21 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('sex', models.CharField(choices=[('NONE', 'Uninitialized'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='NONE', max_length=20, verbose_name='sex')),
                ('date_of_birthday', models.DateTimeField(verbose_name='date of birthday')),
                ('sport', models.CharField(max_length=200, verbose_name='sport')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
