# Generated by Django 2.0.5 on 2018-05-22 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('url', models.URLField(verbose_name='url')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(default='/athletes/default.png', max_length=250, upload_to='', verbose_name='image')),
            ],
            options={
                'verbose_name': 'picture',
                'verbose_name_plural': 'pictures',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('state', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVIEWING', 'Reviewing'), ('PENDING_REVIEW', 'Pending Review')], default='PENDING_REVIEW', max_length=20, verbose_name='state')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
        migrations.AlterModelOptions(
            name='athlete',
            options={'verbose_name': 'athlete', 'verbose_name_plural': 'athletes'},
        ),
        migrations.AlterField(
            model_name='athlete',
            name='state',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVIEWING', 'Reviewing'), ('PENDING_REVIEW', 'Pending Review')], default='PENDING_REVIEW', max_length=20, verbose_name='state'),
        ),
        migrations.AddField(
            model_name='review',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='athletes.Athlete', verbose_name='review'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='picture',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='athletes.Athlete', verbose_name='athlete'),
        ),
        migrations.AddField(
            model_name='link',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='athletes.Athlete', verbose_name='link'),
        ),
    ]
