# Generated by Django 2.0.5 on 2018-05-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_auto_20180522_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='date_of_birthday',
            field=models.DateField(verbose_name='date of birthday'),
        ),
    ]
