# Generated by Django 2.0.5 on 2018-05-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0003_auto_20180522_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='athletes.Athlete', verbose_name='athlete'),
        ),
    ]
