# Generated by Django 2.0.5 on 2018-05-22 11:49

from django.db import migrations, models
import easy_thumbnails.fields
import marketplace.core.files


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0005_auto_20180522_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=20, null=True, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(default='/athletes/default.png', max_length=250, upload_to=marketplace.core.files.UploadToDir('athletes', populate_from='athlete_id'), verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='text'),
        ),
    ]
