# Generated by Django 2.0.5 on 2018-06-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_auto_20180522_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='date_of_birthday',
            new_name='date_of_birth',
        ),
    ]
