# Generated by Django 2.0.5 on 2018-07-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0008_auto_20180615_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='biography'),
        ),
    ]
