# Generated by Django 2.0.5 on 2018-08-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0009_athlete_biography'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='athlete',
            options={'ordering': ('user__date_joined',), 'verbose_name': 'athlete', 'verbose_name_plural': 'athletes'},
        ),
    ]
