# Generated by Django 2.0.5 on 2018-08-30 10:12

from django.db import migrations
import easy_thumbnails.fields
import marketplace.core.files


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0011_auto_20180828_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(max_length=250, upload_to=marketplace.core.files.UploadToDir('athletes', populate_from='athlete_id'), verbose_name='image'),
        ),
    ]
