# Generated by Django 2.0.5 on 2018-09-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0012_auto_20180830_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='is_multimedia',
            field=models.BooleanField(default=False),
        ),
    ]
