# Generated by Django 2.0.5 on 2018-10-10 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import marketplace.core.files
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tokens", "0001_initial"),
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "is_draft",
                    models.BooleanField(
                        default=True,
                        help_text="if the campaign is a draft it isn't complete",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("athlete", "Athlete"), ("club", "Club")], max_length=8
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("description", models.TextField()),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        max_length=250,
                        upload_to=marketplace.core.files.UploadToDir(
                            "campaigns", random_name=True
                        ),
                        verbose_name="image",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Male"), ("female", "Female")],
                        max_length=20,
                        null=True,
                        verbose_name="sex",
                    ),
                ),
                ("height", models.FloatField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("club", models.CharField(blank=True, max_length=128, null=True)),
                ("coach", models.CharField(blank=True, max_length=128, null=True)),
                ("pitch_url", models.URLField(blank=True, null=True)),
                (
                    "pitch_image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        blank=True,
                        max_length=250,
                        null=True,
                        upload_to=marketplace.core.files.UploadToDir(
                            "campaigns", random_name=True
                        ),
                    ),
                ),
                ("ranking", models.CharField(blank=True, max_length=128, null=True)),
                ("biography", models.TextField(blank=True, null=True)),
                ("achievements", models.TextField(blank=True, null=True)),
                ("expected", models.TextField(blank=True, null=True)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("EUR", "EUR"),
                            ("USD", "USD"),
                            ("ETH", "ETH"),
                            ("BTC", "BTC"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("funds", models.FloatField(blank=True, null=True)),
                ("use", models.TextField(blank=True, null=True)),
                ("give_back", models.TextField(blank=True, null=True)),
                ("examples", models.TextField(blank=True, null=True)),
            ],
            options={"ordering": ["-created"]},
        ),
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EUR", "EUR"),
                            ("USD", "USD"),
                            ("ETH", "ETH"),
                            ("BTC", "BTC"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incomes",
                        to="campaigns.Campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("twitter", "Twitter"),
                            ("youtube", "YouTube"),
                            ("linkedin", "LinkedIn"),
                            ("twitch", "Twitch"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                ("url", models.URLField(blank=True, null=True, verbose_name="url")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="campaigns.Campaign",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Picture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        max_length=250,
                        upload_to=marketplace.core.files.UploadToDir(
                            "pictures", random_name=True
                        ),
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pictures",
                        to="campaigns.Campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "image",
                    easy_thumbnails.fields.ThumbnailerImageField(
                        max_length=250,
                        upload_to=marketplace.core.files.UploadToDir(
                            "recommendations", random_name=True
                        ),
                        verbose_name="image",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="campaigns.Campaign",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Revenue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("EUR", "EUR"),
                            ("USD", "USD"),
                            ("ETH", "ETH"),
                            ("BTC", "BTC"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                ("amount", models.FloatField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenues",
                        to="campaigns.Campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sport",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("name", models.TextField(unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="campaign",
            name="sport",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="campaigns.Sport",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="tags",
            field=models.ManyToManyField(blank=True, to="tags.Tag"),
        ),
        migrations.AddField(
            model_name="campaign",
            name="token",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaign",
                to="tokens.Token",
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="revenue", unique_together={("campaign", "year")}
        ),
        migrations.AlterUniqueTogether(
            name="income", unique_together={("campaign", "year")}
        ),
    ]
