# Generated by Django 2.0.5 on 2018-10-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaigns", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="sport",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        )
    ]
