# Generated by Django 2.0.5 on 2018-10-16 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_auto_20181016_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendation',
            old_name='image',
            new_name='file',
        ),
    ]
