# Generated by Django 2.0.5 on 2018-10-17 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0009_auto_20181017_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.TextField(blank=True, null=True, verbose_name='text')),
                ('state', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('reviewing', 'Reviewing'), ('pending_review', 'Pending Review')], default='pending_review', max_length=20, verbose_name='state')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='campaigns.Campaign')),
                ('reviewer', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
                'ordering': ('created',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('reviewer', 'campaign')},
        ),
    ]
