# Generated by Django 2.0.5 on 2018-10-18 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_auto_20181017_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='players',
            field=models.TextField(blank=True, null=True),
        ),
    ]
