# Generated by Django 2.0.5 on 2018-10-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("campaigns", "0011_auto_20181018_0729")]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="started",
            field=models.DateField(
                blank=True,
                help_text="Date when the campaigns started, automatically set when the campaign is approved.",
                null=True,
            ),
        )
    ]
