# Generated by Django 2.0.5 on 2018-10-29 10:08
import datetime

from django.db import migrations

from marketplace.campaigns.constants import APPROVED


def update_started(apps, schema_editor):
    today = datetime.date.today()
    Campaign = apps.get_model("campaigns", "Campaign")
    Campaign.objects.filter(state=APPROVED).update(
        started=today, finished=today + datetime.timedelta(days=90)
    )


def backwards_started(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("campaigns", "0013_auto_20181029_1008")]

    operations = [migrations.RunPython(update_started, backwards_started)]
