# Generated by Django 2.0.8 on 2018-11-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0014_auto_20181029_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='network',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('flickr', 'Flickr'), ('web', 'Web')], max_length=32, null=True),
        ),
    ]
