# Generated by Django 2.0.8 on 2018-11-14 10:57

from django.db import migrations, models
import marketplace.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0016_campaign_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='country',
            field=marketplace.core.fields.CountryCodeField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
