# Generated by Django 2.0.5 on 2018-11-19 16:41
import random

from django.db import migrations

def set_default_color(apps, schema_editor):
    """Set a default color for every existing sport."""
    Sport = apps.get_model("campaigns", "Sport")
    for sport in Sport.objects.all():
        sport.color = hex(random.randint(1, 16777215))[2:]
        sport.save()


def delete_default_color(apps, schema_editor):
    """Deletes the default color"""
    Sport = apps.get_model("campaigns", "Sport")
    for sport in Sport.objects.all():
        sport.color = None
        sport.save()

class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_auto_20181119_1640'),
    ]

    operations = [migrations.RunPython(set_default_color, delete_default_color)]
