# Generated by Django 2.0.5 on 2018-11-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_auto_20181119_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='rating',
            field=models.FloatField(default=4.0),
        ),
    ]
