# Generated by Django 2.0.5 on 2018-11-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_auto_20181121_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='soft_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='rating',
            field=models.FloatField(default=5.0),
        ),
    ]
