# Generated by Django 2.0.5 on 2018-08-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180528_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='Designates if the user has the email verified', verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='restore_password_code',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='restore_password_code_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
