# Generated by Django 2.0.5 on 2018-10-29 15:52

from django.db import migrations
import easy_thumbnails.fields
import marketplace.core.fields
import marketplace.core.files


class Migration(migrations.Migration):

    dependencies = [("users", "0004_user_birth_date")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=easy_thumbnails.fields.ThumbnailerImageField(
                blank=True,
                max_length=250,
                null=True,
                upload_to=marketplace.core.files.UploadToDir("users", random_name=True),
                verbose_name="avatar",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=marketplace.core.fields.CountryCodeField(
                blank=True, max_length=2, null=True
            ),
        ),
    ]
