# Generated by Django 2.0.5 on 2018-08-21 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('actions', '0003_auto_20180820_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='date',
        ),
        migrations.RemoveField(
            model_name='action',
            name='link',
        ),
        migrations.RemoveField(
            model_name='action',
            name='text',
        ),
        migrations.RemoveField(
            model_name='action',
            name='type',
        ),
        migrations.AddField(
            model_name='action',
            name='action_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_actions', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='action',
            name='action_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='actor_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_actions', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='action',
            name='actor_object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_actions', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='action',
            name='target_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='verb',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='actions.Action'),
        ),
        migrations.DeleteModel(
            name='ActionType',
        ),
    ]
