# Generated by Django 2.0.5 on 2018-08-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_auto_20180821_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created',), 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
    ]
