# Generated by Django 2.0.5 on 2018-08-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0005_auto_20180821_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='action_content_type',
            new_name='trigger_content_type',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='action_id',
            new_name='trigger_id',
        ),
    ]
