# Generated by Django 2.0.5 on 2018-08-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0006_auto_20180821_1000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='trigger_id',
            new_name='trigger_object_id',
        ),
        migrations.AddField(
            model_name='action',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='action',
            name='trigger_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trigger_actions', to='contenttypes.ContentType'),
        ),
    ]
