# Generated by Django 2.0.5 on 2018-05-21 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(choices=[('UP', 'Go up'), ('DOWN', 'Go down')], default='UP', max_length=10, verbose_name='rule')),
                ('amount', models.FloatField(verbose_name='amount')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='athletes.Athlete', verbose_name='athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='athletes.Athlete', verbose_name='following')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'supporter',
                'verbose_name_plural': 'supporters',
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='supporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='supporters.Supporter', verbose_name='supporter'),
        ),
    ]
