# Generated by Django 2.0.5 on 2018-05-22 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'alert', 'verbose_name_plural': 'alerts'},
        ),
    ]
