# Generated by Django 2.0.5 on 2018-05-22 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0002_auto_20180522_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='following',
            field=models.ForeignKey(limit_choices_to={'state': 'APPROVED'}, on_delete=django.db.models.deletion.CASCADE, related_name='supporters', to='athletes.Athlete', verbose_name='following'),
        ),
    ]
