# Generated by Django 2.0.5 on 2018-05-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_auto_20180522_1149'),
        ('supporters', '0003_auto_20180522_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporter',
            name='following',
        ),
        migrations.AddField(
            model_name='supporter',
            name='following',
            field=models.ManyToManyField(related_name='suppoters', to='athletes.Athlete', verbose_name='following'),
        ),
    ]
