# Generated by Django 2.0.5 on 2018-05-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0004_auto_20180528_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='suppoters', to='athletes.Athlete', verbose_name='following'),
        ),
    ]
