# Generated by Django 2.0.5 on 2018-06-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0005_auto_20180528_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='following',
            field=models.ManyToManyField(blank=True, limit_choices_to={'state': 'APPROVED'}, related_name='suppoters', to='athletes.Athlete', verbose_name='following'),
        ),
    ]
