# Generated by Django 2.0.5 on 2018-08-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0008_auto_20180821_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ('-created',), 'verbose_name': 'alert', 'verbose_name_plural': 'alerts'},
        ),
    ]
