# Generated by Django 2.0.5 on 2018-08-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supporters', '0009_auto_20180821_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='supporter',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='last name'),
        ),
    ]
